---
common_apt_packages:
  - wget
  - python
  - python-dev
  - python-pip
  - python3
  - python3-dev
  - python3-pip
  - software-properties-common
  - git
  - tmux
  - build-essential
  - cmake
  - clang-6.0
  - libbz2-dev
  - openssl
  - libssl-dev
  - libreadline-dev
  - ctags

pip2_name: pip2
pip3_name: pip3
