---
common_apt_packages:
  - wget
  - python
  - python-dev
  - python-pip
  - python3
  - python3-dev
  - python3-pip
  - software-properties-common
  - git
  - tmux
  - build-essential
  - cmake
  - clang-6.0

# The base directory relative to which user specific configuration files should be stored
default_xdg_config_home: "{{ ansible_env.HOME }}/.config"
config_dir: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"
neovim_ppa: ppa:neovim-ppa/stable
neovim_config_dir: "{{ config_dir }}/nvim"

pip2_name: pip2
pip3_name: pip3
