---
- block:
  - name: Install pyenv
    git:
      repo: https://github.com/pyenv/pyenv.git
      dest: "{{ ansible_env.HOME }}/.pyenv"

  - name: Install pyenv-virtualenv plugin
    git:
      repo: https://github.com/pyenv/pyenv-virtualenv.git
      dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
  when: ansible_distribution == 'Ubuntu'

- block:
  - name: install pyenv via homebrew
    homebrew:
      name: pyenv
      state: present
  - name: install pyenv-virtualenv via homebrew
    homebrew:
      name: pyenv-virtualenv
      state: present
  when: ansible_distribution == 'MacOSX'

- name: Set eval .pyenv in .pyenv_init
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.pyenv_init"
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - '# This file is to init pyenv at your environment'
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'

- name: source .pyenv_init at user init script at ubuntu based system
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    create: yes
    line: "source ${HOME}/.pyenv_init"
  when: ansible_distribution == 'Ubuntu'

- name: source .pyenv_init at user init script at osx based system
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    state: present
    create: yes
    line: "source ${HOME}/.pyenv_init"
  when: ansible_distribution == 'MacOSX'
