---
- block:

  - name: Add neovim ppa
    apt_repository: repo="{{ neovim_ppa }}" state=present
    when: ansible_os_family == "Debian"

  - name: Install neovim from ppa
    apt: name="neovim"

  - name: alternate neovim for vi
    alternatives: name=vi path=/usr/bin/nvim

  - name: alternate neovim for vim
    alternatives: name=vim path=/usr/bin/nvim

  - name: alternate neovim for editor
    alternatives: name=editor path=/usr/bin/nvim

  become: true
  tags:
    neovim

- name: Install neovim python module
  pip:
    name: neovim
    executable: "{{ pip3_name }}"
    extra_args: --user

# Install vim-plug
- block:
  - name: Create "{{ neovim_config_dir }}/autoload" autoload directory
    file: path="{{ neovim_config_dir }}/autoload" state=directory

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ neovim_config_dir }}/autoload/plug.vim"
      force: yes

- block:

  - name: Install personal init.vim
    template:
      src: init.vim.j2
      dest: "{{ neovim_config_dir }}/init.vim"

  - name: Install vim plugins
    command: nvim "+silent! PlugInstall!" +qall!
